# GitHub workflow to automate apickli builds
name: apickli tests

on:
  # push or pull request events to the the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # allow to run this workflow manually on GitHub from the Actions tab
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run all tests
        working-directory: source
        run: |
          npm install
          npm run ci
